//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra8BaseType.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra12FunctionType : _TtC18ShadowTrackerExtra8BaseType
{
    MISSING_TYPE *layout;
    MISSING_TYPE *throws;
    MISSING_TYPE *returnType;
    MISSING_TYPE *argumentTypes;
}

@end

