//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC18ShadowTrackerExtra22_URLEncodedFormEncoder16UnkeyedContainer : _TtCs12_SwiftObject
{
    MISSING_TYPE *codingPath;
    MISSING_TYPE *count;
    MISSING_TYPE *context;
    MISSING_TYPE *boolEncoding;
    MISSING_TYPE *dataEncoding;
    MISSING_TYPE *dateEncoding;
}

@end

