//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra7Session : _TtCs12_SwiftObject
{
    MISSING_TYPE *session;
    MISSING_TYPE *delegate;
    MISSING_TYPE *rootQueue;
    MISSING_TYPE *startRequestsImmediately;
    MISSING_TYPE *requestQueue;
    MISSING_TYPE *serializationQueue;
    MISSING_TYPE *interceptor;
    MISSING_TYPE *serverTrustManager;
    MISSING_TYPE *redirectHandler;
    MISSING_TYPE *cachedResponseHandler;
    MISSING_TYPE *eventMonitor;
    MISSING_TYPE *defaultEventMonitors;
    MISSING_TYPE *requestTaskMap;
    MISSING_TYPE *activeRequests;
    MISSING_TYPE *waitingCompletions;
}

@end

