//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra9ModelType.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra9ClassType : _TtC18ShadowTrackerExtra9ModelType
{
    MISSING_TYPE *layout;
    MISSING_TYPE *super;
}

@end

