//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC18ShadowTrackerExtra17ConvertibleConfigP33_A641A90F1CB1D397792695B568AA1A014Item : _TtCs12_SwiftObject
{
    MISSING_TYPE *modelKey;
    MISSING_TYPE *modelValue;
    MISSING_TYPE *jsonKey;
    MISSING_TYPE *jsonValue;
}

@end

