//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra8BaseType.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra9ModelType : _TtC18ShadowTrackerExtra8BaseType
{
    MISSING_TYPE *properties;
    MISSING_TYPE *genericTypes;
    MISSING_TYPE *modelKeysLock;
    MISSING_TYPE *modelKeys;
    MISSING_TYPE *jsonKeysLock;
    MISSING_TYPE *jsonKeys;
}

@end

