//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra32PinnedCertificatesTrustEvaluator : _TtCs12_SwiftObject
{
    MISSING_TYPE *certificates;
    MISSING_TYPE *acceptSelfSignedCertificates;
    MISSING_TYPE *performDefaultValidation;
    MISSING_TYPE *validateHost;
}

@end

