//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra8BaseType : _TtCs12_SwiftObject
{
    MISSING_TYPE *name;
    MISSING_TYPE *type;
    MISSING_TYPE *kind;
    MISSING_TYPE *module;
    MISSING_TYPE *isSystemModule;
}

@end

