//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra11RetryPolicy.h>

@interface _TtC18ShadowTrackerExtra25ConnectionLostRetryPolicy : _TtC18ShadowTrackerExtra11RetryPolicy
{
}

@end

