//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra19ClosureEventMonitor : _TtCs12_SwiftObject
{
    MISSING_TYPE *sessionDidBecomeInvalidWithError;
    MISSING_TYPE *taskDidReceiveChallenge;
    MISSING_TYPE *taskDidSendBodyData;
    MISSING_TYPE *taskNeedNewBodyStream;
    MISSING_TYPE *taskWillPerformHTTPRedirection;
    MISSING_TYPE *taskDidFinishCollectingMetrics;
    MISSING_TYPE *taskDidComplete;
    MISSING_TYPE *taskIsWaitingForConnectivity;
    MISSING_TYPE *dataTaskDidReceiveData;
    MISSING_TYPE *dataTaskWillCacheResponse;
    MISSING_TYPE *downloadTaskDidFinishDownloadingToURL;
    MISSING_TYPE *downloadTaskDidWriteData;
    MISSING_TYPE *downloadTaskDidResumeAtOffset;
    MISSING_TYPE *requestDidCreateInitialURLRequest;
    MISSING_TYPE *requestDidFailToCreateURLRequestWithError;
    MISSING_TYPE *requestDidAdaptInitialRequestToAdaptedRequest;
    MISSING_TYPE *requestDidFailToAdaptURLRequestWithError;
    MISSING_TYPE *requestDidCreateURLRequest;
    MISSING_TYPE *requestDidCreateTask;
    MISSING_TYPE *requestDidGatherMetrics;
    MISSING_TYPE *requestDidFailTaskEarlyWithError;
    MISSING_TYPE *requestDidCompleteTaskWithError;
    MISSING_TYPE *requestIsRetrying;
    MISSING_TYPE *requestDidFinish;
    MISSING_TYPE *requestDidResume;
    MISSING_TYPE *requestDidResumeTask;
    MISSING_TYPE *requestDidSuspend;
    MISSING_TYPE *requestDidSuspendTask;
    MISSING_TYPE *requestDidCancel;
    MISSING_TYPE *requestDidCancelTask;
    MISSING_TYPE *requestDidValidateRequestResponseDataWithResult;
    MISSING_TYPE *requestDidParseResponse;
    MISSING_TYPE *requestDidValidateRequestResponseWithResult;
    MISSING_TYPE *requestDidCreateUploadable;
    MISSING_TYPE *requestDidFailToCreateUploadableWithError;
    MISSING_TYPE *requestDidProvideInputStream;
    MISSING_TYPE *requestDidFinishDownloadingUsingTaskWithResult;
    MISSING_TYPE *requestDidCreateDestinationURL;
    MISSING_TYPE *requestDidValidateRequestResponseFileURLWithResult;
    MISSING_TYPE *requestDidParseDownloadResponse;
    MISSING_TYPE *queue;
}

@end

