//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra24URLEncodedFormSerializer : _TtCs12_SwiftObject
{
    MISSING_TYPE *alphabetizeKeyValuePairs;
    MISSING_TYPE *arrayEncoding;
    MISSING_TYPE *keyEncoding;
    MISSING_TYPE *spaceEncoding;
    MISSING_TYPE *allowedCharacters;
}

@end

