//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra26NetworkReachabilityManager : _TtCs12_SwiftObject
{
    MISSING_TYPE *reachabilityQueue;
    MISSING_TYPE *reachability;
    MISSING_TYPE *_mutableState;
}

@end

