//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra11DataRequest.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra13UploadRequest : _TtC18ShadowTrackerExtra11DataRequest
{
    MISSING_TYPE *upload;
    MISSING_TYPE *fileManager;
    MISSING_TYPE *uploadable;
}

@end

