//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra8Property : _TtCs12_SwiftObject
{
    MISSING_TYPE *name;
    MISSING_TYPE *type;
    MISSING_TYPE *$__lazy_storage_$_dataType;
    MISSING_TYPE *isVar;
    MISSING_TYPE *offset;
    MISSING_TYPE *ownerType;
}

@end

