//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra11RetryPolicy : _TtCs12_SwiftObject
{
    MISSING_TYPE *retryLimit;
    MISSING_TYPE *exponentialBackoffBase;
    MISSING_TYPE *exponentialBackoffScale;
    MISSING_TYPE *retryableHTTPMethods;
    MISSING_TYPE *retryableHTTPStatusCodes;
    MISSING_TYPE *retryableURLErrorCodes;
}

@end

