//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURLProtocol.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra19EtcHostsURLProtocol : NSURLProtocol
{
    MISSING_TYPE *session;
    MISSING_TYPE *sessionTask;
}

+ (id)canonicalRequestForRequest:(id)arg1;
+ (_Bool)canInitWithRequest:(id)arg1;
- (void).cxx_destruct;
- (id)initWithRequest:(id)arg1 cachedResponse:(id)arg2 client:(id)arg3;
- (void)stopLoading;
- (void)startLoading;

@end

