//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC18ShadowTrackerExtra9SwiftLoad : NSObject
{
}

+ (id)shared;
- (void).cxx_destruct;
- (id)init;
- (void)openLive;
- (void)swiftLoad;

@end

