//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC18ShadowTrackerExtra17MultipartFormData8BodyPart : _TtCs12_SwiftObject
{
    MISSING_TYPE *headers;
    MISSING_TYPE *bodyStream;
    MISSING_TYPE *bodyContentLength;
    MISSING_TYPE *hasInitialBoundary;
    MISSING_TYPE *hasFinalBoundary;
}

@end

