//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra7Request : _TtCs12_SwiftObject
{
    MISSING_TYPE *id;
    MISSING_TYPE *underlyingQueue;
    MISSING_TYPE *serializationQueue;
    MISSING_TYPE *eventMonitor;
    MISSING_TYPE *interceptor;
    MISSING_TYPE *delegate;
    MISSING_TYPE *_mutableState;
    MISSING_TYPE *uploadProgress;
    MISSING_TYPE *downloadProgress;
    MISSING_TYPE *_validators;
}

@end

