//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@interface _TtCC18ShadowTrackerExtra8RSAUtils13RSAUtilsError : NSError
{
}

- (id)initWithDomain:(id)arg1 code:(long long)arg2 userInfo:(id)arg3;
- (id)initWithCoder:(id)arg1;

@end

