//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra7Request.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra11DataRequest : _TtC18ShadowTrackerExtra7Request
{
    MISSING_TYPE *convertible;
    MISSING_TYPE *_mutableData;
}

@end

