//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra11AppDelegate : NSObject
{
    MISSING_TYPE *k6;
    MISSING_TYPE *k12;
    MISSING_TYPE *k13;
    MISSING_TYPE *k24;
    MISSING_TYPE *k25;
    MISSING_TYPE *k26;
    MISSING_TYPE *k27;
    MISSING_TYPE *k28;
    MISSING_TYPE *k29;
    MISSING_TYPE *k30;
    MISSING_TYPE *t1;
    MISSING_TYPE *t2;
    MISSING_TYPE *dns;
    MISSING_TYPE *baseDict;
    MISSING_TYPE *kWidth;
    MISSING_TYPE *MeDeal;
    MISSING_TYPE *timer;
    MISSING_TYPE *timer2;
}

- (void).cxx_destruct;
- (id)init;
- (void)tapIconView;

@end

