//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra8EnumType.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra12OptionalType : _TtC18ShadowTrackerExtra8EnumType
{
    MISSING_TYPE *wrapType;
}

@end

