//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra15SessionDelegate : NSObject
{
    MISSING_TYPE *fileManager;
    MISSING_TYPE *stateProvider;
    MISSING_TYPE *eventMonitor;
}

- (void).cxx_destruct;
- (id)init;

@end

