//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18ShadowTrackerExtra15MultipartUpload : _TtCs12_SwiftObject
{
    MISSING_TYPE *$__lazy_storage_$_result;
    MISSING_TYPE *isInBackgroundSession;
    MISSING_TYPE *multipartFormData;
    MISSING_TYPE *encodingMemoryThreshold;
    MISSING_TYPE *request;
    MISSING_TYPE *fileManager;
}

@end

