//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ShadowTrackerExtra/_TtC18ShadowTrackerExtra19EtcHostsURLProtocol.h>

@interface _TtC18ShadowTrackerExtra19EtcHostsURLProtocol (ShadowTrackerExtra)
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
@end

