//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct ImDrawData {
    _Bool _field1;
    int _field2;
    int _field3;
    int _field4;
    struct ImDrawList **_field5;
    struct ImVec2 _field6;
    struct ImVec2 _field7;
    struct ImVec2 _field8;
};

struct ImDrawList;

struct ImVec2 {
    float _field1;
    float _field2;
};

struct Vector {
    float X;
    float Y;
    float Z;
};

