//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol EtcHostsConfiguration
- (void)resolveHostName:(NSString *)arg1 toIPAddress:(NSString *)arg2;
@end

