//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface MenuView : UIView
{
}

+ (void)fuck;
+ (void)gongneng;
+ (void)kaiqi;
+ (id)MenuView;
+ (void)load;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

