//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MTLBuffer;

@interface MetalBuffer : NSObject
{
    id <MTLBuffer> _buffer;
    double _lastReuseTime;
}

- (void).cxx_destruct;
@property(nonatomic) double lastReuseTime; // @synthesize lastReuseTime=_lastReuseTime;
@property(retain, nonatomic) id <MTLBuffer> buffer; // @synthesize buffer=_buffer;
- (id)initWithBuffer:(id)arg1;

@end

