//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface PUBGlnfohpView : UIView
{
    _Bool _isHP;
    double _progress;
    UIView *_inView;
    double _width;
}

- (void).cxx_destruct;
@property(nonatomic) double width; // @synthesize width=_width;
@property(retain, nonatomic) UIView *inView; // @synthesize inView=_inView;
@property(nonatomic) _Bool isHP; // @synthesize isHP=_isHP;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void)jhSetupViews:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

