//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface PUBGisBone : NSObject
{
    _Bool _Head;
    _Bool _neck;
    _Bool _spine_3;
    _Bool _spine_2;
    _Bool _spine_1;
    _Bool _pelvis;
    _Bool _clavicle_r;
    _Bool _upperarm_r;
    _Bool _lowerarm_r;
    _Bool _hand_r;
    _Bool _clavicle_l;
    _Bool _upperarm_l;
    _Bool _lowerarm_l;
    _Bool _hand_l;
    _Bool _thigh_r;
    _Bool _calf_r;
    _Bool _foot_r;
    _Bool _thigh_l;
    _Bool _calf_l;
    _Bool _foot_l;
}

@property(nonatomic) _Bool foot_l; // @synthesize foot_l=_foot_l;
@property(nonatomic) _Bool calf_l; // @synthesize calf_l=_calf_l;
@property(nonatomic) _Bool thigh_l; // @synthesize thigh_l=_thigh_l;
@property(nonatomic) _Bool foot_r; // @synthesize foot_r=_foot_r;
@property(nonatomic) _Bool calf_r; // @synthesize calf_r=_calf_r;
@property(nonatomic) _Bool thigh_r; // @synthesize thigh_r=_thigh_r;
@property(nonatomic) _Bool hand_l; // @synthesize hand_l=_hand_l;
@property(nonatomic) _Bool lowerarm_l; // @synthesize lowerarm_l=_lowerarm_l;
@property(nonatomic) _Bool upperarm_l; // @synthesize upperarm_l=_upperarm_l;
@property(nonatomic) _Bool clavicle_l; // @synthesize clavicle_l=_clavicle_l;
@property(nonatomic) _Bool hand_r; // @synthesize hand_r=_hand_r;
@property(nonatomic) _Bool lowerarm_r; // @synthesize lowerarm_r=_lowerarm_r;
@property(nonatomic) _Bool upperarm_r; // @synthesize upperarm_r=_upperarm_r;
@property(nonatomic) _Bool clavicle_r; // @synthesize clavicle_r=_clavicle_r;
@property(nonatomic) _Bool pelvis; // @synthesize pelvis=_pelvis;
@property(nonatomic) _Bool spine_1; // @synthesize spine_1=_spine_1;
@property(nonatomic) _Bool spine_2; // @synthesize spine_2=_spine_2;
@property(nonatomic) _Bool spine_3; // @synthesize spine_3=_spine_3;
@property(nonatomic) _Bool neck; // @synthesize neck=_neck;
@property(nonatomic) _Bool Head; // @synthesize Head=_Head;

@end

