//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface PUBGInfoBone : NSObject
{
    struct Vector _Head;
    struct Vector _neck;
    struct Vector _spine_3;
    struct Vector _spine_2;
    struct Vector _spine_1;
    struct Vector _pelvis;
    struct Vector _clavicle_r;
    struct Vector _upperarm_r;
    struct Vector _lowerarm_r;
    struct Vector _hand_r;
    struct Vector _clavicle_l;
    struct Vector _upperarm_l;
    struct Vector _lowerarm_l;
    struct Vector _hand_l;
    struct Vector _thigh_r;
    struct Vector _calf_r;
    struct Vector _foot_r;
    struct Vector _thigh_l;
    struct Vector _calf_l;
    struct Vector _foot_l;
    struct Vector _root;
}

@property(nonatomic) struct Vector root; // @synthesize root=_root;
@property(nonatomic) struct Vector foot_l; // @synthesize foot_l=_foot_l;
@property(nonatomic) struct Vector calf_l; // @synthesize calf_l=_calf_l;
@property(nonatomic) struct Vector thigh_l; // @synthesize thigh_l=_thigh_l;
@property(nonatomic) struct Vector foot_r; // @synthesize foot_r=_foot_r;
@property(nonatomic) struct Vector calf_r; // @synthesize calf_r=_calf_r;
@property(nonatomic) struct Vector thigh_r; // @synthesize thigh_r=_thigh_r;
@property(nonatomic) struct Vector hand_l; // @synthesize hand_l=_hand_l;
@property(nonatomic) struct Vector lowerarm_l; // @synthesize lowerarm_l=_lowerarm_l;
@property(nonatomic) struct Vector upperarm_l; // @synthesize upperarm_l=_upperarm_l;
@property(nonatomic) struct Vector clavicle_l; // @synthesize clavicle_l=_clavicle_l;
@property(nonatomic) struct Vector hand_r; // @synthesize hand_r=_hand_r;
@property(nonatomic) struct Vector lowerarm_r; // @synthesize lowerarm_r=_lowerarm_r;
@property(nonatomic) struct Vector upperarm_r; // @synthesize upperarm_r=_upperarm_r;
@property(nonatomic) struct Vector clavicle_r; // @synthesize clavicle_r=_clavicle_r;
@property(nonatomic) struct Vector pelvis; // @synthesize pelvis=_pelvis;
@property(nonatomic) struct Vector spine_1; // @synthesize spine_1=_spine_1;
@property(nonatomic) struct Vector spine_2; // @synthesize spine_2=_spine_2;
@property(nonatomic) struct Vector spine_3; // @synthesize spine_3=_spine_3;
@property(nonatomic) struct Vector neck; // @synthesize neck=_neck;
@property(nonatomic) struct Vector Head; // @synthesize Head=_Head;

@end

