//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface PUBGInfoColorTools : NSObject
{
    NSArray *_colors;
}

+ (id)tools;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *colors; // @synthesize colors=_colors;
- (id)colorForNumber:(int)arg1;
- (id)init;

@end

