//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <ShadowTrackerExtra/MTKViewDelegate-Protocol.h>

@class MTKView, NSArray, NSMutableArray, NSMutableDictionary, NSString;
@protocol MTLCommandQueue, MTLDevice;

@interface PUBGImGuiDrawView : UIViewController <MTKViewDelegate>
{
    _Bool _test;
    MTKView *_mtkView;
    id <MTLDevice> _device;
    id <MTLCommandQueue> _commandQueue;
    NSArray *_infoArray;
    NSArray *_wuziArray;
    NSMutableArray *_infoViews;
    NSMutableDictionary *_ftViewsInfo;
    struct CGPoint _aimPoint;
}

+ (void)settingViewChange:(_Bool)arg1;
- (void).cxx_destruct;
@property(nonatomic) struct CGPoint aimPoint; // @synthesize aimPoint=_aimPoint;
@property(retain, nonatomic) NSMutableDictionary *ftViewsInfo; // @synthesize ftViewsInfo=_ftViewsInfo;
@property(retain, nonatomic) NSMutableArray *infoViews; // @synthesize infoViews=_infoViews;
@property(retain, nonatomic) NSArray *wuziArray; // @synthesize wuziArray=_wuziArray;
@property(retain, nonatomic) NSArray *infoArray; // @synthesize infoArray=_infoArray;
@property(retain, nonatomic) id <MTLCommandQueue> commandQueue; // @synthesize commandQueue=_commandQueue;
@property(retain, nonatomic) id <MTLDevice> device; // @synthesize device=_device;
@property(retain, nonatomic) MTKView *mtkView; // @synthesize mtkView=_mtkView;
@property(nonatomic) _Bool test; // @synthesize test=_test;
- (void)updateUIImage:(id)arg1 images:(id)arg2;
- (void)updateView:(id)arg1 views:(id)arg2;
- (id)fetchUIImage:(id)arg1 index:(long long)arg2;
- (id)directViewForMode:(id)arg1;
- (void)hiddelAllDirectViews;
- (id)fetchView:(id)arg1 index:(long long)arg2;
- (void)configWithData:(id)arg1 aimPos:(struct CGPoint)arg2;
- (void)doTheJob;
- (void)mtkView:(id)arg1 drawableSizeWillChange:(struct CGSize)arg2;
- (void)drawInMTKView:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)updateIOWithTouchEvent:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

