//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class PUBGInfoModel, UILabel;

@interface PUBGDirectView : UIView
{
    PUBGInfoModel *_model;
    unsigned long long _number;
    UILabel *_numberLbl;
    UILabel *_distLbl;
}

+ (id)directView;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *distLbl; // @synthesize distLbl=_distLbl;
@property(retain, nonatomic) UILabel *numberLbl; // @synthesize numberLbl=_numberLbl;
@property(nonatomic) unsigned long long number; // @synthesize number=_number;
@property(retain, nonatomic) PUBGInfoModel *model; // @synthesize model=_model;
- (id)initWithFrame:(struct CGRect)arg1;

@end

