//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class PUBGImGuiDrawView;

@interface PUBGImGuiLoad : NSObject
{
    PUBGImGuiDrawView *_vna;
}

+ (id)share;
- (void).cxx_destruct;
@property(retain, nonatomic) PUBGImGuiDrawView *vna; // @synthesize vna=_vna;
- (void)initshow;
- (void)show;

@end

