//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, PUBGInfoBone, PUBGisBone;

@interface PUBGInfoModel : NSObject
{
    _Bool _isAI;
    int _isArms;
    long long _number;
    NSString *_name;
    double _distance;
    double _hp;
    PUBGInfoBone *_bone;
    PUBGisBone *_isbone;
    long long _flag;
    struct CGRect _rect;
}

+ (id)getName:(const unsigned short *)arg1 t:(char *)arg2 l:(unsigned long long)arg3 f:(int)arg4;
- (void).cxx_destruct;
@property(nonatomic) long long flag; // @synthesize flag=_flag;
@property(retain, nonatomic) PUBGisBone *isbone; // @synthesize isbone=_isbone;
@property(retain, nonatomic) PUBGInfoBone *bone; // @synthesize bone=_bone;
@property(nonatomic) int isArms; // @synthesize isArms=_isArms;
@property(nonatomic) _Bool isAI; // @synthesize isAI=_isAI;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(nonatomic) double hp; // @synthesize hp=_hp;
@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long number; // @synthesize number=_number;

@end

